development:
  adapter: postgresql
  encoding: utf8
  database: project_branko_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_branko_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>

production:
  adapter: postgresql
  encoding: utf8
  database: project_branko_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>